#!/bin/bash
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-present Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

# compile and copy amlogic autoscript files to part1
mcopy $RELEASE_DIR/3rdparty/bootloader/*autoscript :: 2>&1 > /dev/null || true

if [ -a "$RELEASE_DIR/3rdparty/bootloader/aml_autoscript" ]; then
      echo "image: creating Amlogic ZIP env-update package"
	  pushd $RELEASE_DIR/3rdparty/bootloader > /dev/null
	  zip -q env-update.zip aml_autoscript
      echo "image: signing the env-update package"
      mkdir -p sign
      SIGNAPK_DIR="$ROOT/tools/signapk"
      java -Xmx1024m -jar $SIGNAPK_DIR/signapk.jar -w $SIGNAPK_DIR/testkey.x509.pem $SIGNAPK_DIR/testkey.pk8 env-update.zip sign/aml_autoscript.zip
	  popd > /dev/null
      mcopy $RELEASE_DIR/3rdparty/bootloader/sign/aml_autoscript.zip ::
fi

# copy device trees to part1
for dtb in $RELEASE_DIR/3rdparty/bootloader/device_trees $RELEASE_DIR/3rdparty/bootloader/*.dtb $RELEASE_DIR/3rdparty/bootloader/dtb.img ; do
  [ -e "$dtb" ] && mcopy -s "$dtb" ::
done

if [ -f "$RELEASE_DIR/3rdparty/bootloader/u-boot" ]; then
  echo "Writing u-boot to $(basename $DISK)"
  dd if="$RELEASE_DIR/3rdparty/bootloader/u-boot" of="$DISK" conv=fsync,notrunc bs=1 count=112 >"$SAVE_ERROR" 2>&1 || show_error
  dd if="$RELEASE_DIR/3rdparty/bootloader/u-boot" of="$DISK" conv=fsync,notrunc bs=512 skip=1 seek=1 >"$SAVE_ERROR" 2>&1 || show_error
fi

if [ -f "$RELEASE_DIR/3rdparty/bootloader/boot.ini" ]; then
  mcopy $RELEASE_DIR/3rdparty/bootloader/boot.ini ::
fi

if [ -f "$RELEASE_DIR/3rdparty/bootloader/config.ini" ]; then
  mcopy $RELEASE_DIR/3rdparty/bootloader/config.ini ::
fi
